server:
  port: 8666
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: project-gateway
  datasource:
    url: ${db.user.url}
    username: ${db.user.username}
    password: ${db.user.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.96.168.139
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis-plus:
  mapper-locations: mapper/*.xml