server:
  port: 8666
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: project-gateway
  datasource:
    url: jdbc:mysql://localhost:3300/gateway
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis-plus:
  mapper-locations: mapper/*.xml